# Generated by Django 5.2.4 on 2025-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0002_rfidreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidcommandlog',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
