# Generated by Django 5.2.4 on 2025-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0004_queuedcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedcommand',
            name='device_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queuedcommand',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
