# Generated by Django 5.2.4 on 2025-07-26 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0007_rename_command_queuedcommand_command_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text='Optional tag for this RFID', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set False to unauthorize the RFID')),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='queuedcommand',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rfidcommandlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rfidreply',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
