# Generated by Django 5.2.4 on 2025-07-28 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0009_rfidauthorizationstatus_delete_authorizedrfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text='Optional tag for this RFID', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set False to unauthorize the RFID')),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='RFIDAuthorizationStatus',
        ),
    ]
