# Generated by Django 5.2.4 on 2025-07-29 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0010_authorizedrfid_delete_rfidauthorizationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('action', models.CharField(choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized')], max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthorizedRFID',
        ),
    ]
