# Generated by Django 5.0.14 on 2025-08-02 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0013_rename_rfidstatus_rfidauthorization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDAuthorizationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='IMEI of the GPS device', max_length=64)),
                ('vehicle_id', models.CharField(blank=True, help_text='Optional vehicle identifier', max_length=64, null=True)),
                ('command_code', models.CharField(default='146', help_text='Command code sent to GPS device', max_length=10)),
                ('rfid', models.CharField(help_text='RFID number sent for verification', max_length=500)),
                ('status', models.CharField(choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized'), ('Unknown', 'Unknown')], help_text='Status reported by GPS device', max_length=16)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when REPLY received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
