# Generated by Django 5.2.4 on 2025-07-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('vehicle_id', models.IntegerField()),
                ('device_id', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('Authorize', 'Authorize'), ('Unauthorize', 'Unauthorize'), ('CheckStatus', 'CheckStatus')], max_length=20)),
                ('rfid_list', models.JSONField()),
                ('command_code', models.CharField(max_length=5)),
                ('formatted_string', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
