# Generated by Django 5.2.4 on 2025-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('command_code', models.CharField(max_length=5)),
                ('rfid', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
