# Generated by Django 5.2.4 on 2025-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0003_alter_rfidcommandlog_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
                ('vehicle_id', models.IntegerField()),
                ('command', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
