# Generated by Django 5.2.4 on 2025-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0005_alter_queuedcommand_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidreply',
            name='device_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rfidreply',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
