# Generated by Django 5.2.4 on 2025-07-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0006_alter_rfidreply_device_id_alter_rfidreply_vehicle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuedcommand',
            old_name='command',
            new_name='command_string',
        ),
    ]
