# Generated by Django 5.2.4 on 2025-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0008_authorizedrfid_alter_queuedcommand_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDAuthorizationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('rfid', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthorizedRFID',
        ),
    ]
