# Generated by Django 5.2.4 on 2025-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0011_rfidstatus_delete_authorizedrfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidstatus',
            name='action',
        ),
        migrations.AddField(
            model_name='rfidstatus',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfidstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized')], max_length=20, null=True),
        ),
    ]
