# Generated by Django 5.0.14 on 2025-07-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0012_remove_rfidstatus_action_rfidstatus_device_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RFIDStatus',
            new_name='RFIDAuthorization',
        ),
        migrations.RenameModel(
            old_name='QueuedCommand',
            new_name='RFIDAuthorizationQueue',
        ),
        migrations.RenameModel(
            old_name='RFIDReply',
            new_name='RFIDAuthorizationReply',
        ),
    ]
