# Generated by Django 5.2.4 on 2025-07-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0014_rfidauthorizationcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidauthorizationcheck',
            name='vehicle_id',
        ),
    ]
