# Generated by Django 5.2.4 on 2025-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0015_remove_rfidauthorizationcheck_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidauthorizationcheck',
            name='vehicle_id',
            field=models.CharField(blank=True, help_text='Optional vehicle identifier', max_length=64, null=True),
        ),
    ]
