# Generated by Django 5.2.4 on 2025-08-02 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0016_rfidauthorizationcheck_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_imei', models.CharField(max_length=20)),
                ('rfid_device_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_swiped', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('activity_status', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('local_time', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
