# Generated by Django 5.2.4 on 2025-08-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0017_gpsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GpsData',
        ),
    ]
