# Generated by Django 5.0.14 on 2025-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0018_delete_gpsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidauthorizationqueue',
            name='command_code',
            field=models.CharField(blank=True, help_text='Command code sent to GPS device', max_length=10, null=True),
        ),
    ]
