# Generated by Django 5.0.14 on 2025-08-02 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0019_rfidauthorizationqueue_command_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidauthorizationcheck',
            name='created_at',
        ),
        migrations.AddField(
            model_name='rfidauthorizationcheck',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationcheck',
            name='is_swiped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfidauthorizationcheck',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationcheck',
            name='local_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationcheck',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationcheck',
            name='timestamp',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationreply',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationreply',
            name='is_swiped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfidauthorizationreply',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationreply',
            name='local_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationreply',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidauthorizationreply',
            name='timestamp',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rfidauthorizationcheck',
            name='command_code',
            field=models.CharField(default='146', max_length=10),
        ),
        migrations.AlterField(
            model_name='rfidauthorizationcheck',
            name='device_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rfidauthorizationcheck',
            name='received_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rfidauthorizationcheck',
            name='rfid',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rfidauthorizationcheck',
            name='status',
            field=models.CharField(choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized'), ('Unknown', 'Unknown')], max_length=16),
        ),
        migrations.AlterField(
            model_name='rfidauthorizationcheck',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rfidauthorizationreply',
            name='received_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
