# Generated by Django 5.0.14 on 2025-08-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0020_remove_rfidauthorizationcheck_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidauthorizationcheck',
            name='is_swiped',
        ),
        migrations.RemoveField(
            model_name='rfidauthorizationreply',
            name='is_swiped',
        ),
    ]
