# Generated by Django 5.0.14 on 2025-08-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0021_remove_rfidauthorizationcheck_is_swiped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidauthorizationcheck',
            name='local_time',
        ),
        migrations.RemoveField(
            model_name='rfidauthorizationreply',
            name='local_time',
        ),
    ]
