# Generated by Django 5.0.14 on 2025-08-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_api', '0022_remove_rfidauthorizationcheck_local_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidauthorizationcheck',
            old_name='timestamp',
            new_name='gps_timestamp',
        ),
        migrations.RenameField(
            model_name='rfidauthorizationreply',
            old_name='timestamp',
            new_name='gps_timestamp',
        ),
    ]
